CREATE DATABASE sentiment_analysis DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE sentiment_analysis.entry (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
original TEXT NOT NULL,
processed TEXT,
class INT NOT NULL,
error BIT(1) DEFAULT 0 NOT NULL
);

INSERT INTO sentiment_analysis.entry (original, class) VALUES
('Stety niestety mam dość wyraźny obraz naszego handlu z różnych pozycji obserwacji.Zakupy robię czasem planowo czasem na raty impulsowo różnie.Dziś papierosy i małe co nie co dla siebie na drogę traf chce dokonuję w markecie Carrefour ( dawniej jako delikatesy (?)Viki).Sklep średnich rozmiarów samoobsługowy z ladą ser wędlina w głębi tradycyjnym stoiskiem alkoholowym i na sali sprzedaży trzecie stoisko z obsługą z wyrobami cukierniczymi.Ot taki spożywczo przemysłowy sklep.Nie jestem w nim po raz pierwszy nie po raz pierwszy spotykam się z obojętną a czasem wręcz opryskliwą obsługą która klienta traktuje jak personę no gratę.Panie wykładające towar blokują przejście i nie wykazują minimum chęci by dokładanie towaru nie utrudniało towaru.A jest to możliwe tak by nie zagradzać w poprzek wózkiem alejki .No cóż zakupy nie zawsze jak widać muszą być przyjemne.Przystaję przy ladzie tam gdzie są ciastka na wagę .Nie ma tu pracownika.Już chciałam podejść do kasy ogólnej ale nie zdążyłam bo pracownik się zjawia.Pani zła jak bąk jeszcze coś przełyka w biegu.Potwierdza się jak Polak głodny to zły a ekspedientka nie chybnie nie dojadła.Bardzo w opryskliwy sposób zirytowana skanuje zakupy .Nie mam dobrej oceny po dzisiejszych tu zakupach.Ceny przeciętne, mieszane.Asortyment pod markami własnymi i brandami powszechnymi.Na drugi raz bardzo mocno się zastanowię czy nie ominąć tego sklepu szerokim łukiem.A zakupy tu nie traktować jako ostateczną ostateczność.Można płacić kartą.Nie polecam.Zakupy na własne ryzyko.Sklep w centralnym punkcie Pragi Północ.', 0),
('Koszmarna koszmarność internetowego sklepu Yves Roche .Niestety tu zawsze zakupy są trudne i absolutnie do przyjemnych ich zaliczyć nie można.Skuszona jednakże ofertą @ od Payback który ma być promocja dla nowego sklepu uczestniczącego w programie ( choć faktycznie YR w programie PB jest już od jakiegoś dłuższego czasu).Skompletowałam koszyk, po czym się zalogowałam.Komunikat że kwota 101 Pln jest mniejsza (!!!) od 99 według systemu firmy kod został anulowany ponowne jego wprowadzenie, komunikat o błędzie.Na prawde odechciewa się zakupów i nawet najbardziej atrakcyjne i kuszące promocje chyba nie są tego warte.',0),
('Brakuje mi skali niestety w te stronę negatywną by móc ocenić to co się dzieje na portalu jakoscobslugi.pl Jeszcze parę miesięcy mogła bym napisać naszym a dziś..... cóż każdy obserwator widzi co się dzieje a dzieje się bardzo bardzo źle.Firma nie odpowiada, jawnie i bez skrepowania Nas lekceważy.Brak przepływu informacji, klarownych i wiążących decyzji po stronie pracowników VSC do której to firmy należy strona i cały projekt.Tak źle chyba nigdy jeszcze nie było.Nikła nadzieja na poprawę wszystko wskazuje na totalny,bezpowrotny upadek.',0) ,
('Jestem zła i nie zmienia tego fakt że się spodziewałam że tak będzie.Za kod spod nakrętki postanawiam zamówić starter.Loguję się na swoje konto w programie wprowadzam kod.Ok .Kod zaakceptowany komunikat i kod uprawniający mnie do odbioru startera .Informacja że został do mnie on też wysłany na podany adres @ .Wszystko ok.Kod albo muszę wydrukować albo zapisać.…......Idę do salonu na kobielskiej, nie mam starterów promocyjnych.W Tesco Gocław może będą w piątek.Na Rembielińskiej nie ma i nie wiadomo czy blendą .A w King Cross Praga jeżeli będą to nie wcześniej jak w poniedziałek.Minus dla Coca coli i minus dla Play.Obie firmy prowadzą promocję obie według mnie są winne fatalnej logistyce nagród.',0),
('Do rossmana wstąpiłem celem wywołania zdjęć. W pierwszej alejce stał konsultant ubrany w baiły, firmowy fartuch. Zapytałem czy można skorzystać z automatu do wywowływania zdjęć. Konsultant zaprowadził pod automat, krok po kroku wyjaśnił instrukcje obsługi, powiedział jaka są ceny usługi i od czego uzależnione. W samym sklepie panuje porządek. Półki, podłoga są czyste, wolne od kurzu.',1),
('Cukiernia umieszczona jest na wprost głównego wejścia do galerii. Trudno jest przejść obojętnie obok tylu słodkości. Wybór jest zróżnicowany, ceny przystępne. Pracownik zapytał mnie "co podać". Poprosiłem o jedna porcje wybranego ciasta. Ciasta są na wage. Wziąłem ciasto na wynos, także pracownik zapakował produkt w tekturowe opakowanie. Pracownik ubrany był w firmowy, kremowy fartuch. Obsługa był miła, uprzejma, profesjonalna.',1)
