CREATE DATABASE sentiment_analysis DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE sentiment_analysis.entry (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
original TEXT NOT NULL,
processed TEXT,
class INT NOT NULL,
error BIT(1) DEFAULT 0 NOT NULL
);

INSERT INTO sentiment_analysis.entry (original, class) VALUES
('Stety niestety mam dość wyraźny obraz naszego handlu z różnych pozycji obserwacji.Zakupy robię czasem planowo czasem na raty impulsowo różnie.Dziś papierosy i małe co nie co dla siebie na drogę traf chce dokonuję w markecie Carrefour ( dawniej jako delikatesy (?)Viki).Sklep średnich rozmiarów samoobsługowy z ladą ser wędlina w głębi tradycyjnym stoiskiem alkoholowym i na sali sprzedaży trzecie stoisko z obsługą z wyrobami cukierniczymi.Ot taki spożywczo przemysłowy sklep.Nie jestem w nim po raz pierwszy nie po raz pierwszy spotykam się z obojętną a czasem wręcz opryskliwą obsługą która klienta traktuje jak personę no gratę.Panie wykładające towar blokują przejście i nie wykazują minimum chęci by dokładanie towaru nie utrudniało towaru.A jest to możliwe tak by nie zagradzać w poprzek wózkiem alejki .No cóż zakupy nie zawsze jak widać muszą być przyjemne.Przystaję przy ladzie tam gdzie są ciastka na wagę .Nie ma tu pracownika.Już chciałam podejść do kasy ogólnej ale nie zdążyłam bo pracownik się zjawia.Pani zła jak bąk jeszcze coś przełyka w biegu.Potwierdza się jak Polak głodny to zły a ekspedientka nie chybnie nie dojadła.Bardzo w opryskliwy sposób zirytowana skanuje zakupy .Nie mam dobrej oceny po dzisiejszych tu zakupach.Ceny przeciętne, mieszane.Asortyment pod markami własnymi i brandami powszechnymi.Na drugi raz bardzo mocno się zastanowię czy nie ominąć tego sklepu szerokim łukiem.A zakupy tu nie traktować jako ostateczną ostateczność.Można płacić kartą.Nie polecam.Zakupy na własne ryzyko.Sklep w centralnym punkcie Pragi Północ.', 0),
('Koszmarna koszmarność internetowego sklepu Yves Roche .Niestety tu zawsze zakupy są trudne i absolutnie do przyjemnych ich zaliczyć nie można.Skuszona jednakże ofertą @ od Payback który ma być promocja dla nowego sklepu uczestniczącego w programie ( choć faktycznie YR w programie PB jest już od jakiegoś dłuższego czasu).Skompletowałam koszyk, po czym się zalogowałam.Komunikat że kwota 101 Pln jest mniejsza (!!!) od 99 według systemu firmy kod został anulowany ponowne jego wprowadzenie, komunikat o błędzie.Na prawde odechciewa się zakupów i nawet najbardziej atrakcyjne i kuszące promocje chyba nie są tego warte.',0),
('Brakuje mi skali niestety w te stronę negatywną by móc ocenić to co się dzieje na portalu jakoscobslugi.pl Jeszcze parę miesięcy mogła bym napisać naszym a dziś..... cóż każdy obserwator widzi co się dzieje a dzieje się bardzo bardzo źle.Firma nie odpowiada, jawnie i bez skrepowania Nas lekceważy.Brak przepływu informacji, klarownych i wiążących decyzji po stronie pracowników VSC do której to firmy należy strona i cały projekt.Tak źle chyba nigdy jeszcze nie było.Nikła nadzieja na poprawę wszystko wskazuje na totalny,bezpowrotny upadek.',0) ,
('Jestem zła i nie zmienia tego fakt że się spodziewałam że tak będzie.Za kod spod nakrętki postanawiam zamówić starter.Loguję się na swoje konto w programie wprowadzam kod.Ok .Kod zaakceptowany komunikat i kod uprawniający mnie do odbioru startera .Informacja że został do mnie on też wysłany na podany adres @ .Wszystko ok.Kod albo muszę wydrukować albo zapisać.…......Idę do salonu na kobielskiej, nie mam starterów promocyjnych.W Tesco Gocław może będą w piątek.Na Rembielińskiej nie ma i nie wiadomo czy blendą .A w King Cross Praga jeżeli będą to nie wcześniej jak w poniedziałek.Minus dla Coca coli i minus dla Play.Obie firmy prowadzą promocję obie według mnie są winne fatalnej logistyce nagród.',0),
('Do rossmana wstąpiłem celem wywołania zdjęć. W pierwszej alejce stał konsultant ubrany w baiły, firmowy fartuch. Zapytałem czy można skorzystać z automatu do wywowływania zdjęć. Konsultant zaprowadził pod automat, krok po kroku wyjaśnił instrukcje obsługi, powiedział jaka są ceny usługi i od czego uzależnione. W samym sklepie panuje porządek. Półki, podłoga są czyste, wolne od kurzu.',1),
('Cukiernia umieszczona jest na wprost głównego wejścia do galerii. Trudno jest przejść obojętnie obok tylu słodkości. Wybór jest zróżnicowany, ceny przystępne. Pracownik zapytał mnie "co podać". Poprosiłem o jedna porcje wybranego ciasta. Ciasta są na wage. Wziąłem ciasto na wynos, także pracownik zapakował produkt w tekturowe opakowanie. Pracownik ubrany był w firmowy, kremowy fartuch. Obsługa był miła, uprzejma, profesjonalna.',1),
('Po nieudanej próbie wypłacenia pieniędzy w oddziale banku Poolbank przy ul.Grójeckiej 53/57 udałem się do oddziału w Al.Jerozolimskich 109. Bank jest widoczny z ulicy więc nie miałem problemu ze znalezieniem go. Po wejściu do środka powitała mnie pani w wieku około 25 lat z czarnymi włosami. Nie wstając z za biurka spytała mnie w czym może mi pomóc. Odpowiedziałem że szukam kasy aby wypłacić pieniądze. Pani, wciąż siedząc pokazała gdzie jest kasa ale dodała że jest tam klient i muszę poczekać. Trochę się zdziwiłem, bo zawsze w takich sytuacjach słyszę "proszę poczekać" a tu "musi pan poczekać". No ale cóż może to specyfika tego banku. Poczekałem zatem. Tradycyjnie obejrzałem w tym czasie oddział. Było czysto, dla oczekujących klientów stała czerwona kanapa z żółtymi poduszkami. Na biurkach pracowników panował porządek. Po krótkim oczekiwaniu kasa była wolna. Przy kasie powitała mnie pani w wieku około 25 lat. Szybko i sprawnie wypłaciła pieniądze a na koniec z uśmiechem pożegnała mnie.',1),
('Po pracy umówiłem się ze znajomymi na spotkanie. Kolega zaproponował nową pizzerię w Śródmieściu. Przed wejściem do lokalu było czysto, szyby nie były zabrudzone a po wejściu powitany zostałem przez uśmiechniętą obsługę słowami "dzień dobry". Ponieważ lokal był dwupoziomowy wybraliśmy stolik na piętrze. Po zajęciu miejsc podeszła do nas pani o wzroście około 160 cm, mająca około 25 lat i krótkie, ciemne włosy. Podała karty i spytała czy podać na początek coś do picia. Przeglądając menu, zauważyłem dość dużą różnorodność dań i napojów. Wybrane potrawy podane były w ciekawy sposób i wyglądały apetycznie. Mimo iż wystrój lokalu był dość prosty to czas spędzony tam wspominam bardzo miło. Minusem była tylko zbyt mała toaleta. Korzystać z niej mogła na raz tylko jedna osoba. W lokalu było bardzo czysto a obsługa bardzo miła i dyskretna. Ceny posiłków były adekwatne do jakości potraw ale ceny napojów już nie. Picie było za drogie tak jak i małe desery.',1),
('Jadąc z Lublina do Warszawy zatrzymałem się w stylowej restauracji. Oprócz jedzenia można tam było również przenocować w drewnianych i murowanych domkach. Duży neon informował już z daleka o tym miejscu. Parking był duży i czysty. Wnętrze lokalu wykonane było z drewna i miało tzw. klimat. Duże stoliki, wygodne krzesła i kanapy zachęcały do dłuższego posiedzenia i odpoczęcia od jazdy. Po zajęciu miejsca, podeszła do stolika pani z obsługi. Miała około 40 lat, dłuższe czarne włosy i uśmiech na twarzy. Pani powiedziała "dzień dobry", podała kartę z menu i odeszła do innych klientów. Po około 5-8 minutach wróciła i przyjęła zamówienie. Na potrawy czekałem około 15 minut. Były duże i apetycznie podane. Jedzenie było gorące i smaczne. Na dodatek tego jak płaciłem zorientowałem się, że posiłki były też niedrogie. Na stole leżał czysty obrus, sztućce były czyste a całe miejsce było stylowo oświetlone. Pani z obsługi była bardzo miła i czuć było, że to jej naturalne zachowanie. Bardzo polecam to miejsce!',1),
('W trakcie płacenia za zakupy zostałem poinformowany przez kasjerkę o możliwości otrzymania karty kredytowej sieci REAL. Aby otrzymać więcej informacji zaproszony zostałem do stanowiska "Real finanse". Po podejściu do stoiska zauważyłem, że jest ono wolne i nie muszę czekać na obsługę. Z uśmiechem i słowami "dzień dobry, zapraszam" zostałem powitany przez młodą uśmiechniętą panią (imię do mojej wiadomości). W sposób przejrzysty, zwięzły wytłumaczono mi zasady otrzymanie karty kredytowej i płynące z tego korzyści. Ponieważ przekazana informacja była dla mnie atrakcyjna postanowiłem podpisać umowę. Szybko i sprawnie pani wypełniła (lewą ręką) potrzebne druki, resztę wydrukowała. Chętnie odpowiadała też na moje liczne i dociekliwe pytania. Na biurku panował porządek, blat był czysty a pani była schludnie ubrana w strój służbowy. Na koniec zostałem pożegnany z uśmiechem słowami "dziękuję bardzo za wizytę, zapraszam do robienia zakupów w sieci Real". SUPER obsługa!',1),
('Lokal znajduje się w jednej z trzech ''budek'', w trójkącie ograniczonym ulicami Radiowa, Gołuchowska i Wrocławska (w wierzchołku blisko dwóch pierwszych ulic, wejście od strony Radiowej). Trafiłem tam przez zupełny przypadek, a skusiłem się niezwykle niską ceną męskiego strzyżenia - 9 zł.Wewnątrz salon prezentował się przeciętnie. Utrzymany był w czystości, ale minimalistyczny i surowy wystrój przypominał czasy PRLu. Pożółkłe dyplomy, niektóre sprzed kilkudziesięciu lat, dodawały wrażenia zacofania.Po odczekaniu umówionych 20 minut zostałem zaproszony na fotel. Prosiłem o proste, standardowe strzyżenie - boki na 3 mm, góra na około 18 mm. Gdy fryzjerka podziękowała mi, zwróciłem uwagę na nierówności. Wyraźnie odstawało mi coś z prawej strony głowy, co spotkało się z komentarzem, że odgniotłem to sobie podczas snu (dziwne, bo wcześniej umyłem głowę). Widziałem też, że boki nie są symetryczne, co z kolei fryzjerka zwaliła na kształt mojej czaszki. Dodatkowo w domu obejrzałem się dokładnie z tyłu i miałem potworne schody! Zmuszony byłem prosić współlokatora o skrócenie i wyrównanie wszystkiego maszynką domową i choć był w tej kwestii zupełnym amatorem, to zrobił do znacznie lepiej niż (dyplomowana?) fryzjerka salonu Fryzjernia.Jakość obsługi, a w szczególności kompetencje i umiejętności fryzjerki, oceniam bardzo nisko. Na podniesienie ogólnej oceny wpływa ma czystość salonu oraz niskie ceny (choć ich stosunek do jakości jest dalece niezadowalający).',0),
('Dotyczy UP Warszawa 35.Tak skandalicznej organizacji obsługi nie przeżyłem nigdy, dawno też nie podniesiono mi tak bardzo ciśnienia. Na poczcie chciałem odebrać awizowany list – była to moja pierwsza wizyta w tej placówce. Po wejściu zauważyłem, że nie ma systemu numerkowego i trzeba ustawić się w kolejce. Spytałem, kto ostatni i jeden z klientów powiedział, że zależy do czego – paczki okienko nr 5, reszta tutaj (okienko 3). Zająłem kolejkę, ale podszedłem jeszcze do okienka nr 5, by upewnić się, że poza symbolem paczek nie różni się niczym od okienka 3.W międzyczasie w obu kolejkach zaczęło przybywać ludzi. Gdy podszedłem do okienka 3, pracownica poczty uniesionym głosem stwierdziła, że awiza w okienku 5! Powiedziałem, że na tym okienku też jest napis „awizo”, na co usłyszałem już niemal krzyk, że tu jest awizo finansowe! Musiałem stać ponownie w kolejce! Żałuję tylko, że nie zapisałem nazwiska tej pani i nie poprosiłem kierownika – oczywiście jednak napiszę skargę.Poza mną do okienka nr 5 odesłano jeszcze jedną osobę, po czym okazało się, że nie ma więcej nikogo z opłatami, więc pani z okienka nr 3 wstała, podeszła do okienka nr 5 i zaczęła brać od klientów awiza! Pracownice poczty same sobie utrudniają pracę! Na poczcie nie było żadnej informacji, z jakimi sprawami należy kierować się do poszczególnych okienek, oczekujący klienci zaczęli mówić, że kiedyś można było awiza realizować w każdym okienku – czemu więc nie można obsługi na tej poczcie po prostu sensownie zorganizować? Oznaczenia okienek też sygnalizują coś innego niż twierdzą pracownice - słowo "awizo" nie różni się niczym od słowa "awizo", a jednak wmówiono mi, że jedno z nich oznacza awizo finansowe. Jest to jakiś absurd i czyjś wymysł, który nie ma zastosowania w praktyce! Do tego zachowanie pracownicy jest poniżej krytyki. Coś takiego pamiętają chyba tylko czasy PRLu! Chciałbym więcej na tę pocztę nie wracać.',0)
